/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface MyComponent {
        /**
          * Friendly label to demonstrate prop passing in generated samples.
          * @default 'value'
         */
        "prop": string;
    }
    interface SampleButton {
        /**
          * Button style variant used in generated samples.
          * @default 'primary'
         */
        "type": ButtonVariant;
    }
    interface SampleCard {
        /**
          * Headline for the card surface.
          * @default 'Heading'
         */
        "heading": string;
        /**
          * Status badge label rendered in the header.
          * @default 'Draft'
         */
        "status": string;
        /**
          * Supporting summary text displayed beneath the heading.
          * @default 'Summary text goes here.'
         */
        "summary": string;
    }
    interface SampleCardAction {
        /**
          * Optional link target for the action.
         */
        "href"?: string;
        /**
          * Text label displayed for the action.
          * @default 'Action'
         */
        "label": string;
        /**
          * Visual variant for the action control.
          * @default 'primary'
         */
        "variant": ActionVariant;
    }
    interface SampleInput {
        /**
          * Label displayed above the input field.
          * @default 'Label'
         */
        "label": string;
        /**
          * Placeholder text shown inside the input.
          * @default 'Type something...'
         */
        "placeholder": string;
    }
}
declare global {
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLSampleButtonElement extends Components.SampleButton, HTMLStencilElement {
    }
    var HTMLSampleButtonElement: {
        prototype: HTMLSampleButtonElement;
        new (): HTMLSampleButtonElement;
    };
    interface HTMLSampleCardElement extends Components.SampleCard, HTMLStencilElement {
    }
    var HTMLSampleCardElement: {
        prototype: HTMLSampleCardElement;
        new (): HTMLSampleCardElement;
    };
    interface HTMLSampleCardActionElement extends Components.SampleCardAction, HTMLStencilElement {
    }
    var HTMLSampleCardActionElement: {
        prototype: HTMLSampleCardActionElement;
        new (): HTMLSampleCardActionElement;
    };
    interface HTMLSampleInputElement extends Components.SampleInput, HTMLStencilElement {
    }
    var HTMLSampleInputElement: {
        prototype: HTMLSampleInputElement;
        new (): HTMLSampleInputElement;
    };
    interface HTMLElementTagNameMap {
        "my-component": HTMLMyComponentElement;
        "sample-button": HTMLSampleButtonElement;
        "sample-card": HTMLSampleCardElement;
        "sample-card-action": HTMLSampleCardActionElement;
        "sample-input": HTMLSampleInputElement;
    }
}
declare namespace LocalJSX {
    interface MyComponent {
        /**
          * Friendly label to demonstrate prop passing in generated samples.
          * @default 'value'
         */
        "prop"?: string;
    }
    interface SampleButton {
        /**
          * Button style variant used in generated samples.
          * @default 'primary'
         */
        "type"?: ButtonVariant;
    }
    interface SampleCard {
        /**
          * Headline for the card surface.
          * @default 'Heading'
         */
        "heading"?: string;
        /**
          * Status badge label rendered in the header.
          * @default 'Draft'
         */
        "status"?: string;
        /**
          * Supporting summary text displayed beneath the heading.
          * @default 'Summary text goes here.'
         */
        "summary"?: string;
    }
    interface SampleCardAction {
        /**
          * Optional link target for the action.
         */
        "href"?: string;
        /**
          * Text label displayed for the action.
          * @default 'Action'
         */
        "label"?: string;
        /**
          * Visual variant for the action control.
          * @default 'primary'
         */
        "variant"?: ActionVariant;
    }
    interface SampleInput {
        /**
          * Label displayed above the input field.
          * @default 'Label'
         */
        "label"?: string;
        /**
          * Placeholder text shown inside the input.
          * @default 'Type something...'
         */
        "placeholder"?: string;
    }
    interface IntrinsicElements {
        "my-component": MyComponent;
        "sample-button": SampleButton;
        "sample-card": SampleCard;
        "sample-card-action": SampleCardAction;
        "sample-input": SampleInput;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
            "sample-button": LocalJSX.SampleButton & JSXBase.HTMLAttributes<HTMLSampleButtonElement>;
            "sample-card": LocalJSX.SampleCard & JSXBase.HTMLAttributes<HTMLSampleCardElement>;
            "sample-card-action": LocalJSX.SampleCardAction & JSXBase.HTMLAttributes<HTMLSampleCardActionElement>;
            "sample-input": LocalJSX.SampleInput & JSXBase.HTMLAttributes<HTMLSampleInputElement>;
        }
    }
}
