/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface MyComponent {
        /**
          * Friendly label to demonstrate prop passing in generated samples.
          * @default 'value'
         */
        "prop": string;
    }
    interface SampleButton {
        /**
          * Button style variant used in generated samples.
          * @default 'primary'
         */
        "type": ButtonVariant;
    }
}
declare global {
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLSampleButtonElement extends Components.SampleButton, HTMLStencilElement {
    }
    var HTMLSampleButtonElement: {
        prototype: HTMLSampleButtonElement;
        new (): HTMLSampleButtonElement;
    };
    interface HTMLElementTagNameMap {
        "my-component": HTMLMyComponentElement;
        "sample-button": HTMLSampleButtonElement;
    }
}
declare namespace LocalJSX {
    interface MyComponent {
        /**
          * Friendly label to demonstrate prop passing in generated samples.
          * @default 'value'
         */
        "prop"?: string;
    }
    interface SampleButton {
        /**
          * Button style variant used in generated samples.
          * @default 'primary'
         */
        "type"?: ButtonVariant;
    }
    interface IntrinsicElements {
        "my-component": MyComponent;
        "sample-button": SampleButton;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
            "sample-button": LocalJSX.SampleButton & JSXBase.HTMLAttributes<HTMLSampleButtonElement>;
        }
    }
}
